### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [smalinin/netserializer2#1]
Hey,
since netserializer is often used in network operations it would be good to have support for async when dealing with a NetworkStream.

Can you add `Task DeserializeAsync(...)` and `Task SerializeAsync(...)` ?

**Comment by smalinin** [comment]
You could free do it. Also I am not sure, that the methods above are required. You could simple create packed with next structure on one side ` { int len

**Comment by smalinin** [comment]
You could free do it. Also I am not sure, that the methods above are required. You could create data packet via => serialize Data to MemoryStream and than, send DataLen and Data byte array via Network(or etc) to an another side, where you could create MemoryStream and deserialize the data and etc. So you problem is related with implementation/creation of network protocol for your app.

**Comment by asdfgasdfsafgsdfa** [comment]
You're right this solution would do everything I want as well.
I didn't think of that, thank you.
